<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
%>
# Setup the reports folders and prefix filename with date-timestamp
<%
unless Dir.exist?("reports")
	Dir.mkdir('reports')
end

Dir.chdir("reports")

puts "\n>>> TEST REPORT will be filed in the following path:\n" + Dir.pwd + "\/\n\n"

reportfile = "reports\/test-report.html"

Dir.chdir("..")
%>

<% common = "--tags ~@wip --tags ~@ignore --strict" %>

# DEFAULT PROFILE: executed through command without explicit profile switch 'bundle exec cucumber'
# Also used by IntelliJ(IDE) for running tests
default: --profile which-live

# ENVIRONMENT PROFILES: At the moment running with no profile (default) is the same as appending "-p staging"
valtech-live: TARGET=valtech-live --profile html_report <%= common%> features

# COMMON RUNTIME PROFILES: these profiles are part of other profiles, cannot be run on their own.

html_report: --format pretty --format html --out <%= reportfile%> --format junit --out reports

# TAG PROFILES
wip: --tags @wip:3 --wip features
valtech: --tags @valtech --tags ~@wip

# DEBUG PROFILES: Must be run in conjuction with an environment profile above
browser: IN_BROWSER=true PAUSE=1 <%= common%> features
browser_chrome: IN_BROWSER_CHROME=true <%= common%> features
debug: DEBUG=true <%= common%> features